version: '2'
services:
    jhipsterflywayweb-app:
        image: jhipsterflywayweb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://jhipsterflywayweb-mssql:1433;database=jhitest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterflywayweb-mssql:
        extends:
            file: mssql.yml
            service: jhipsterflywayweb-mssql
